### ISSUE TITLE
fatal error after activation

### ISSUE THREAD

**Issue by danlum** [obenland/the-bootstrap#4]
i tried to troubleshoot the best i can, and i'm sure it's a simple error i don't know about.  i've uploaded 1.2.5 via ftp, activated.  i get this error:

Fatal error: Call to undefined function wp_get_theme() in /home/content/19/9169419/html/pfeweb/wp-content/themes/obenland-the-bootstrap-8224391/functions.php on line 799

i've deactivated plugins i think may be problematic, and cleared the cache.  what am i missing?  running wp 3.3.1 on self-hosted, is it only 3.4 compatible?

thanks.

**Comment by obenland** [comment]
Hi danlum,

thank you for giving me feedback! I'm sorry that you have had a bad  experience with my theme.

It's odd, that you would get this error message, since there is an explicit version check implemented, to get to the correct function.

Could you do me a favor and try this version with you WordPress install:
http://wordpress.org/extend/themes/download/the-bootstrap.1.2.5.zip?nostats=1

Are you running the current 3.3.1 or a development version of WordPress?

Thanks again,
Konstantin

**Comment by danlum** [comment]
that one didn't work either.  3.3.1, not a dev version.  it's probably me, not the theme.  i'm sure i made a security change or something along the way and messed things up.
